name: AutoBackup Jualan
on:
  schedule:
    - cron: 0 */24 * * *
  workflow_dispatch:
jobs:
  ProsesBackup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Menginstall Rclone
      run: curl https://rclone.org/install.sh | sudo bash
    - name: Memuat konfigurasi Rclone
      run: |
        mkdir -p ~/.config/rclone/
        cat >  ~/.config/rclone/rclone.conf  << EOF
        ${{ secrets.rclone }}
        EOF
    - name: Penyalinan
      run: |
        rclone delete drdel: --drive-use-trash=false --rmdirs && rclone copy "3dr:backup" "4dr:backup" --drive-server-side-across-configs --max-age 24h
